name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "mirror.hychiiu.com"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "mirror.hychiiu.com"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.mirror.hychiiu.com", custom_domain = true },
  { pattern = "quay.mirror.hychiiu.com", custom_domain = true },
  { pattern = "gcr.mirror.hychiiu.com", custom_domain = true },
  { pattern = "k8s-gcr.mirror.hychiiu.com", custom_domain = true },
  { pattern = "k8s.mirror.hychiiu.com", custom_domain = true },
  { pattern = "ghcr.mirror.hychiiu.com", custom_domain = true },
  { pattern = "cloudsmith.mirror.hychiiu.com", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.mirror.hychiiu.com", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
